local STRINGS       = GLOBAL.STRINGS
-- Strings
STRINGS.NAMES.BOOK_NOTEBOOK = "笔记本"
STRINGS.RECIPE_DESC.BOOK_NOTEBOOK = "好记性不如烂笔头！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_NOTEBOOK = "我是不是应该记下笔记呢？"
STRINGS.NOTEBOOK    =
{
    BOOKTITLELEFT   = "《",
    BOOKTITLERIGHT  = "》",
    BUTTON_CANCEL   = "取消",
    BUTTON_CLEAR    = "清除",
    BUTTON_ACCEPT   = "确定",
    BUTTON_LASTPAGE = "上一页",
    BUTTON_NEXTPAGE = "下一页",
}