local _G            = GLOBAL
local STRINGS       = _G.STRINGS
-- Strings
STRINGS.NAMES.BOOK_NOTEBOOK = "筆記本"
STRINGS.RECIPE_DESC.BOOK_NOTEBOOK = "好記性不如爛筆頭！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_NOTEBOOK = "我是不是應該記下筆記呢？"
STRINGS.NOTEBOOK    =
{
    BOOKTITLELEFT   = "《",
    BOOKTITLERIGHT  = "》",
    BUTTON_CANCEL   = "取消",
    BUTTON_CLEAR    = "清除",
    BUTTON_ACCEPT   = "確定",
    BUTTON_LASTPAGE = "上一頁",
    BUTTON_NEXTPAGE = "下一頁",
}

_G.LOCALISATION     = "tchinese"